[build]
# assuming the gutenberg site is in a docs folder, if it isn't you don't need
# to have a `base` variable but you do need the `publish` and `command`
base    = "gutenberg"
publish = "gutenberg/public"
command = "gutenberg build"

[build.environment]
# Set the version name that you want to use and Netlify will automatically use it
GUTENBERG_VERSION = "0.3.3"

# The magic for deploying previews of branches
# We need to override the base url with what the url of the preview is ($DEPLOY_PRIME_URL)
# otherwise links would not work properly
[context.deploy-preview]
command = "gutenberg build --base-url $DEPLOY_PRIME_URL"

# https://gitlab.com/gitlab-org/gitlab-ce/merge_requests?scope=all&utf8=%E2%9C%93&state=merged&author_username=travismiller
[[redirects]]
  from = "/gitlab-merged"
  to = "https://bit.ly/travismiller-gitlab-merged"

# http://contributors.gitlab.com/contributors/travis-miller/commits
[[redirects]]
  from = "/gitlab-contributor"
  to = "https://bit.ly/travismiller-gitlab-contributor"